import { Paper } from './types';

type PaperInit = Omit<Paper, 'reviewStatus'>;

export const PAPERS_PART1: PaperInit[] = [
  {
    id: "zhou-2025",
    title: "A collaborative large language model for drug analysis.",
    authors: ["Zhou H", "Liu F", "Wu J", "Zhang W", "Huang G", "Clifton L", "Eyre D", "Luo H", "Branson K", "Schwab P", "Wu X", "Zheng Y", "Thakur A", "Clifton DA"],
    year: 2025,
    journal: "Nat Biomed Eng",
    doi: "10.1038/s41551-025-01471-z",
    abstract: "Proposes DrugGPT, a knowledge-grounded collaborative LLM for accurate, evidence-based recommendations for clinical decisions. Evaluated on drug/dosage recommendations and drug-drug interactions.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS for Pharmacology", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Outperforms existing LLMs with fewer parameters", "Achieves state-of-the-art across all metrics", "Reduces hallucinations via knowledge-grounding"]
  },
  {
    id: "rudolph-2026",
    title: "GPT-4o in Nutrition for Inpatients Undergoing Post-Stroke Rehabilitation: Identifying Dietary Errors, AI-Expert Collaboration.",
    authors: ["García-Rudolph A", "Hernandez-Pena E", "Del Cacho N", "Teixidó-Font C", "Wright MA", "Opisso E"],
    year: 2026,
    journal: "J Am Nutr Assoc",
    doi: "10.1080/27697061.2025.2571878",
    abstract: "Evaluates GPT-4o's ability to identify dietary errors in hospital menus and explores structured AI-expert collaboration in clinical workflows.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["High accuracy (Kappa 0.892)", "AI follows strict rules whereas dietitians incorporate patient tolerance", "Supports role as a prescreening tool"]
  },
  {
    id: "liu-2026",
    title: "LLM-driven collaborative framework for knowledge-enhanced cancer pain assessment and management.",
    authors: ["Liu H", "Hu Y", "Li D", "Shi B", "Niu Y", "Zhang X", "Zheng G", "Li C", "Wang L", "Bao Y"],
    year: 2026,
    journal: "NPJ Digit Med",
    doi: "10.1038/s41746-026-02362-6",
    abstract: "OncoPainBot simulates reasoning of multiple experts via specialized agents (Extraction, Mechanism Reasoning, Planning, Safety-Check) for personalized analgesic care.",
    themes: ["LLM-based MAS in Oncology", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Decision accuracy of 0.841", "High consistency with real-world clinical documents", "Reliable drug selection verified by experts"]
  },
  {
    id: "tang-2025",
    title: "Bridging Data Gaps in Oncology: Large Language Models and Collaborative Filtering for Cancer Treatment Recommendations.",
    authors: ["Tang T", "Li A", "Tan X", "Ji Q", "Si L", "Bao L"],
    year: 2025,
    journal: "medRxiv",
    doi: "10.1101/2025.04.07.25325243",
    abstract: "Combines LLMs for trial extraction with collaborative filtering to suggest treatments for rare cancers using structured data from ClinicalTrials.gov.",
    themes: ["LLM-based MAS in Oncology", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Identified clinically meaningful new treatments for melanoma", "Successfully cover 78 cancer types and 5,315 interventions", "Predictive accuracy ranges 0.49-0.62 RMSE"]
  },
  {
    id: "wang-2025-neuro",
    title: "LLM-based multi-agent system for neuro-ophthalmic diagnosis and personalized treatment planning.",
    authors: ["Wang W"],
    year: 2025,
    journal: "Front Neurosci",
    doi: "10.3389/fnins.2025.1688509",
    abstract: "Multi-agent framework (Information Collection + Diagnosis Agents) that preserves diagnostic uncertainty to support neuro-ophthalmic screening.",
    themes: ["LLM-based MAS in Specialized Diagnosis", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Improves robustness over single-model baselines", "Uncertainty-aware fusion for downstream triage", "Ensembles multiple LLMs with CNN image branches"]
  },
  {
    id: "li-2025-alzheimer",
    title: "CARE-AD: a multi-agent large language model framework for Alzheimer's disease prediction using longitudinal clinical notes.",
    authors: ["Li R", "Wang X", "Berlowitz D", "Mez J", "Lin H", "Yu H"],
    year: 2025,
    journal: "NPJ Digit Med",
    doi: "10.1038/s41746-025-01940-4",
    abstract: "CARE-AD uses specialized agents to extract AD symptoms and predict onset up to 10 years before diagnosis from longitudinal EHR notes.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Specialized Diagnosis"],
    keyFindings: ["Accuracy of 0.53 vs 0.26-0.45 for single models", "Effective early risk assessment", "Collaborative diagnostic emulation"]
  },
  {
    id: "inoue-2025",
    title: "DruGagent: Multi-Agent Large Language Model-Based Reasoning for Drug-Target Interaction Prediction.",
    authors: ["Inoue Y", "Song T", "Wang X", "Luna A", "Fu T"],
    year: 2025,
    journal: "ArXiv",
    doi: "N/A",
    abstract: "Multi-agent system (AI, KG, and Search agents) combining specialized perspectives with transparent CoT and ReAct reasoning for drug-target interaction.",
    themes: ["LLM-based MAS for Pharmacology", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["45% F1 score improvement over non-reasoning GPT-4o mini", "Detailed, human-interpretable reasoning", "KG agent most impactful after AI agent"]
  },
  {
    id: "wan-2025",
    title: "DeepGut: A collaborative multimodal large language model framework for digestive disease assisted diagnosis.",
    authors: ["Wan XH", "Liu MX", "Zhang Y", "Kou GJ", "Xu LQ", "Liu H", "Yang XY", "Zuo XL", "Li YQ"],
    year: 2025,
    journal: "World J Gastroenterol",
    doi: "10.3748/wjg.v31.i31.109948",
    abstract: "Four-tiered multimodal framework integrating info extraction, chain construction, suggestion, and risk analysis for gastrointestinal diseases.",
    themes: ["LLM-based Multi-modal MAS", "LLM-based MAS in Specialized Diagnosis", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["97.8% diagnostic accuracy", "Outperforms single-modal LLM tools significantly", "High experts commendation for logical coherence"]
  },
  {
    id: "liu-2025-orders",
    title: "Optimizing Order Sets With a Large Language Model-Powered Multiagent System.",
    authors: ["Liu S", "Huang SS", "McCoy AB", "Wright AP", "Horst S", "Wright A"],
    year: 2025,
    journal: "JAMA Netw Open",
    doi: "10.1001/jamanetworkopen.2025.33277",
    abstract: "Multiagent system (Critique, Search, Knowledge Retrieval, Medication Verification) to identify improvements in clinical order sets.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["19% of generated suggestions were rated as useful", "Scalable approach for CDSS enhancement", "Improved alignment (Kappa 0.41) after expert alignment"]
  },
  {
    id: "xu-2025-hypothesis",
    title: "Multi agent large language models for biomedical hypothesis generation in drug combination discovery.",
    authors: ["Xu Q", "Soto C", "Shahnawaz M", "Liu X", "Jiang X", "Kim Y"],
    year: 2025,
    journal: "iScience",
    doi: "10.1016/j.isci.2025.113984",
    abstract: "Coated-LLM employs specialized Researcher, Reviewer, and Moderator agents to generate and evaluate drug combination hypotheses for Alzheimer's.",
    themes: ["LLM-based MAS for Pharmacology", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Accuracy: 0.74 vs 0.52 for traditional methods", "Experimentally validated drug combination efficacy", "Scalable approach for scientific reasoning"]
  },
  {
    id: "ke-2024",
    title: "Mitigating Cognitive Biases in Clinical Decision-Making Through Multi-Agent Conversations.",
    authors: ["Ke Y", "Yang R", "Lie SA", "Lim TXY", "Ning Y", "Li I", "Abdullah HR", "Ting DSW", "Liu N"],
    year: 2024,
    journal: "J Med Internet Res",
    doi: "10.2196/59439",
    abstract: "Simulates clinical dynamics (Devil's Advocate, Expert, Facilitator) to counter confirmation bias, anchoring bias, and premature closure.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["76% diagnostic accuracy vs human evaluators", "Corrects misconceptions even with misleading initial data", "Framework 4-C performed best"]
  },
  {
    id: "akinseloyin-2026",
    title: "Large language model-based multiagent collaboration for abstract screening toward automated systematic reviews.",
    authors: ["Akinseloyin O", "Jiang X", "Palade V"],
    year: 2026,
    journal: "Biol Methods Protoc",
    doi: "10.1093/biomethods/bpag006",
    abstract: "Evaluates majority voting, multi-agent debate, and adjudication strategies for automated systematic review abstract screening.",
    themes: ["LLM-based MAS for Healthcare Workflow", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Up to 68% workload reduction", "Majority voting is the best cost-effective strategy", "Multi-agent debate improves weaker models most"]
  },
  {
    id: "miao-2026",
    title: "MedARC: Adaptive multi-agent refinement and collaboration for enhanced medical reasoning.",
    authors: ["Miao Y", "Wen J", "Luo Y", "Li J"],
    year: 2026,
    journal: "Int J Med Inform",
    doi: "10.1016/j.ijmedinf.2025.106136",
    abstract: "Medical Agent Refinement and Collaboration (MedARC) framework for structured debate, cross-agent summarization, and confidence-aware aggregation.",
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Boosts PubMedQA accuracy by 4.3%", "Human evaluation confirms gains in factual consistency", "Structured summarization module independent contribution to performance"]
  },
  {
    id: "hoazt-2026",
    title: "DILIConsult: A Multi-Agent Large Language Model Framework for Evaluating Drug-Induced Liver Injury.",
    authors: ["Ho AZT", "Law JZF", "Wang A", "Lim DYZ", "Ong JCL"],
    year: 2026,
    journal: "Pharmacotherapy",
    doi: "10.1002/phar.70131",
    abstract: "Agentic pipeline based on GPT-4o for parsing clinical history and LiverTox data to analyze suspected liver injury in ICU patients.",
    themes: ["LLM-based MAS in Specialized Diagnosis", "LLM-based MAS for Pharmacology", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Superior knowledge recall over clinicians", "Task division minimizes information loss in long histories", "Reasoning aligned with medical consensus"]
  },
  {
    id: "kim-2026-scoping",
    title: "From non-agentic large language models to multi-agent systems in emergency medicine: a scoping review.",
    authors: ["Kim H", "Jo S", "Lim MH", "Choi DH"],
    year: 2026,
    journal: "Clin Exp Emerg Med",
    doi: "10.15441/ceem.26.136",
    abstract: "Scoping review of 35 studies on non-agentic vs agentic LLM systems in emergency departments, identifying gaps in workflow-aware design.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS for Healthcare Workflow", "LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["Shift from task-level to multi-agent role coordination noted", "Highlight need for prospective safety validation", "Concentrated on triage, diagnosis, and documentation"]
  },
  {
    id: "le-2025-activity",
    title: "A Multi-Agent LLM Network for Suggesting and Correcting Human Activity and Posture Annotations.",
    authors: ["Le H", "Choube A", "Swain VD", "Mishra V", "Intille S"],
    year: 2025,
    journal: "Proc ACM Int Conf Ubiquitous Comput",
    doi: "10.1145/3714394.3756185",
    abstract: "Adapts GLOSS multi-agent system to triangulate self-reports and passive sensor data for improved activity recognition labels.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["63-75% agreement with human recall", "Corrects common human annotation errors", "Scalable approach for real-world behavior monitoring"]
  },
  {
    id: "wang-2025-auto",
    title: "Autonomous Analysis of Curated Patient Data Using a Large Language Model-Based Multiagent Framework.",
    authors: ["Wang J", "Swoboda DM", "Nazha A"],
    year: 2025,
    journal: "JCO Clin Cancer Inform",
    doi: "10.1200/CCI-25-00176",
    abstract: "Six-party AI agent system (Planning, Data Retrieval, Cleaning, Statistics, Review) to automate replication of bone marrow transplant primary outcomes.",
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Oncology"],
    keyFindings: ["53.3% outcome replication vs 35% for ChatGPT 4o", "No hallucinations observed in multiagent approach", "Most failures due to data transformation issues"]
  },
  {
    id: "hasjim-2026",
    title: "A multiagent large language model-based system to simulate the liver transplant selection committee.",
    authors: ["Hasjim BJ", "Azarfar G", "Lee FG", "Diwan TS", "Raju S", "Gross JA", "Sidhu A", "Ichii H", "Krishnan RG", "Mamdani M", "Sharma D", "Bhat M"],
    year: 2026,
    journal: "Lancet Digit Health",
    doi: "10.1016/j.landig.2025.100966",
    abstract: "Simulates MDT discussions (Hepatologist, Surgeon, Cardiologist, Social Worker) to improve objective treatment rationing in liver transplants.",
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["92% accuracy in predicting 1-year survival", "98.19% Identifying absolute contraindications", "Step toward objective transplatation selection"]
  },
  {
    id: "chen-2026-diagnosis",
    title: "Independent and collaborative performance of large language models and healthcare professionals in diagnosis and triage.",
    authors: ["Chen M", "Wu Y", "Ma J", "Jia X", "Gao C", "Zhao F", "Qiao Y"],
    year: 2026,
    journal: "NPJ Digit Med",
    doi: "10.1038/s41746-026-02409-8",
    abstract: "Meta-analysis of 50 studies comparing LLMs and clinicians across specialties, exploring collaborative (Human + AI) performance gains.",
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Clinical Decision-making", "LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["LLM-assisted HCPs outperformed HCPs alone", "Diagnostic accuracy improved by 13% for top-1 diagnoses", "Relative accuracy of LLMs vs HCPs improved with model diversity"]
  },
  {
    id: "sun-2026-debate",
    title: "Model confrontation and collaboration (MCC): A debate intelligence framework for medical reasoning.",
    authors: ["Sun X", "Hong Q", "Zhang M", "Li Y", "Chen T", "Huang Z", "Liang G", "Tang W", "Xu S", "Ni X", "Pang J", "Wan P", "Long E"],
    year: 2026,
    journal: "Cell Rep Med",
    doi: "10.1016/j.xcrm.2025.102547",
    abstract: "Iteratively refines medical reasoning through multi-round structured confrontation and collaboration among diverse models.",
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["92.6% accuracy on MedQA", "Outperformed domain-specific Med-PaLM 2", "80% top-1 accuracy in complex diagnostic dialog tasks"]
  },
  {
    id: "shi-2024-aki",
    title: "AKI-Detector: Integrating ML and LLMs for Early Prediction of Acute Kidney Injury in ICU.",
    authors: ["Shi T", "Xiao M", "Xu H", "Zhao H", "Kong G"],
    year: 2024,
    journal: "AMIA Annu Symp Proc",
    doi: "N/A",
    abstract: "Multi-agent framework combining EHR-based machine learning with LLMs and RAG for explainable AKI prediction.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS in Specialized Diagnosis"],
    keyFindings: ["Accuracy of 0.827 on MIMIC-IV cohort", "Reduces hallucinations via ML model integration", "Bridged gap to clinically interpretable reports"]
  },
  {
    id: "li-2025-icd",
    title: "Improving Rare and Common ICD Coding via a Multi-Agent LLM-Based Approach.",
    authors: ["Li R", "Wang X", "Yu H"],
    year: 2025,
    journal: "ACM CIKM",
    doi: "10.1145/3746252.3760894",
    abstract: "Five role-specific agents (Patient, Physician, Coder, Reviewer, Adjuster) simulating real-world medical coding with SOAP structures.",
    themes: ["LLM-based MAS for Healthcare Workflow", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Outperformed CoT and self-consistency", "Competitive with fine-tuned models", "Significantly improved coding of rare conditions"]
  },
  {
    id: "gopalakrishnan-2025",
    title: "Advancements in Multi-Agent Large Language Model Systems in Healthcare and Diagnostics.",
    authors: ["Gopalakrishnan A", "Ramya G", "Preethiya T", "Paranthaman RN", "Ashwini S", "Dhwarithaa R"],
    year: 2025,
    journal: "Advancements in Multi-Agent LLM Systems",
    doi: "10.4018/979-8-3373-1419-8.ch002",
    abstract: "Overview of technical implementation including guardrails, self-reflection, and EHR integration for precision medicine.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["Emphasizes scalability and specialization", "Discusses IoT and natural language interface integration", "Focus on decision transparency and explainable AI"]
  },
  {
    id: "chen-2025-self",
    title: "A Self-Evolving Framework for Multi-Agent Medical Consultation Based on Large Language Models.",
    authors: ["Chen K", "Qi J", "Huo J", "Tian P", "Meng F", "Yang X", "Gao Y"],
    year: 2025,
    journal: "IEEE ICASSP",
    doi: "10.1109/ICASSP49660.2025.10889517",
    abstract: "SeM-Agents framework with residual structure and self-evolving experience databases to refine consultation rationality.",
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["89.2% accuracy on MedQA", "Incremental improvement via Correct Consultation Experience Database", "Safety review layer for human-aligned decisions"]
  },
  {
    id: "liu-2025-medchat",
    title: "MedChat: A Multi-Agent Framework for Multimodal Diagnosis with Large Language Models.",
    authors: ["Liu PR", "Bansal S", "Dinh J", "Pawar A", "Satishkumar R", "Desai S", "Gupta N", "Wang X", "Hu S"],
    year: 2025,
    journal: "IEEE MIPR",
    doi: "10.1109/MIPR67560.2025.00078",
    abstract: "Coordinates specialized vision models with role-specific agents for interactive diagnostic glaucoma reporting.",
    themes: ["LLM-based Multi-modal MAS", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Specialized Diagnosis"],
    keyFindings: ["Reduces hallucination risk in imaging reports", "Tailored interface for clinical/educational use", "Director agent coordination improves reliability"]
  },
  {
    id: "deng-2025-cardio",
    title: "LLM-augmented multi-agent cooperative framework for medical case retrieval in cardiology.",
    authors: ["Deng L", "Hu H", "Lu K", "He P"],
    year: 2025,
    journal: "J King Saud Univ Comput Inf Sci",
    doi: "10.1007/s44443-025-00311-z",
    abstract: "Iterative planner-retriever model architecture to find factual cases and literature while reformulating complex cardiology queries.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Improved recall by 6.1 points", "Robust to query noise and novel conditions", "Mitigates hallucinations via evidence-based relevance estimator"]
  },
  {
    id: "sorin-2026-ethics",
    title: "Alignment of large language models in solving medical ethical dilemmas.",
    authors: ["Sorin V", "Glicksberg BS", "Korfiatis P", "Collins JD", "Yeow ME", "Brandeland M", "Nadkarni GN", "Klang E"],
    year: 2026,
    journal: "Digital Health",
    doi: "10.1177/20552076261428395",
    abstract: "Stress tests 14 LLMs on adapted 'Trolley dilemmas' to evaluate deontological versus utilitarian reasoning in clinical contexts.",
    themes: ["LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["6.3% of outputs recommended impermissible actions", "Large variance in utilitarian bias between models", "Motivates benchmarked evaluation of refusal behaviors"]
  },
  {
    id: "wang-2025-rescue",
    title: "Self-Aware Intelligent Medical Rescue Unmanned Team via Large Language Model and Multi-Agent Reinforcement Learning.",
    authors: ["Wang X", "Zhi G", "Tang Z", "Jin H", "Zhang Q", "Li N"],
    year: 2025,
    journal: "ACM ICP",
    doi: "10.1145/3744103.3744144",
    abstract: "Decomposes complex medical rescue rescue tasks into subtasks using CMA-LLM and hierarchical reinforcement learning for unmanned equipment.",
    themes: ["LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Improved learning coordination among rescue agents", "Hierarchical method reduces observation space", "Modular architecture generalizes to new rescue scenarios"]
  },
  {
    id: "sun-2025-humanmod",
    title: "HumanMoD: A multi-RAG collaborative LLM for inclusive urban public healthcare services.",
    authors: ["Sun S", "Zhong Z", "Yu N", "Gong X", "Yang K"],
    year: 2025,
    journal: "Applied Soft Computing",
    doi: "10.1016/j.asoc.2025.113684",
    abstract: "Mixture-of-Doctors module for parallel diagnostic streams in underserved communities, ensuring groundedness via RAG.",
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Outperformed state-of-the-art on MedQA", "No parameter adjustment required for deployment", "Bridges gaps for socially vulnerable groups"]
  },
  {
    id: "wang-2025-colacare",
    title: "ColaCare: Enhancing Electronic Health Record Modeling through Large Language Model-Driven Multi-Agent Collaboration.",
    authors: ["Wang Z", "Zhu Y", "Zhao H", "Zheng X", "Sui D", "Wang T", "Tang W", "Wang Y", "Harrison E", "Pan C", "Gao J", "Ma L"],
    year: 2025,
    journal: "ACM Web Conf",
    doi: "10.1145/3696410.3714877",
    abstract: "Integrates numerical expert model predictions with LLM-based reasoning via MetaAgent orchestration and MDT-style debate.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Superior performance in mortality and readmission prediction", "Bridges gap between structured data and text reasoning", "RAG module addresses medical knowledge currency"]
  },
  {
    id: "han-2025-vocare",
    title: "VoCare AI: A Multi-Agent LLM Workflow for Improved Clinic Operational Efficiency.",
    authors: ["Han DLJ", "Ng PC", "Low MYH"],
    year: 2025,
    journal: "IEEE TENCON",
    doi: "10.1109/TENCON66050.2025.11375163",
    abstract: "Voice-first assistant utilizing specialized agents for scheduling, billing, and FAQs to support elderly patients in polyclinics.",
    themes: ["LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["ASR WER of 22.22% for Singlish", "1.00 groundedness in RAG module", "Streamlined administrative burden for healthcare staff"]
  },
  {
    id: "kim-2024-adaptive",
    title: "MDAgents: An Adaptive Collaboration of LLMs for Medical Decision-Making.",
    authors: ["Kim Y", "Park C", "Jeong H", "Chan YS", "Xu X", "McDuff D", "Lee H", "Ghassemi M", "Breazeal C", "Park HW"],
    year: 2024,
    journal: "NeurIPS",
    doi: "N/A",
    abstract: "Automatically assigns solo or group collaboration structure based on task difficulty and medical complexity classification.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Best performance in 7/10 benchmarks", "Moderator review + RAG improved accuracy by 11.8%", "Effective classification of task difficulty compared to physicians"]
  },
  {
    id: "barbato-2026",
    title: "Structured Clinical Reasoning in AI: Comparing LLMs and Curated, Ontology-Grounded Multi-Agent Systems.",
    authors: ["Barbato F", "Sorichetti F", "Ielo E", "Megliola L"],
    year: 2026,
    journal: "LNCS",
    doi: "10.1007/978-3-032-12092-2_23",
    abstract: "KaiMed platform built on GPT-4o-mini and proprietary ontology, literature graph, and safety filters for auditable reasoning.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["KaiMed surfaces fenotypically specific investigational options", "Ontology grounding ensures semantic integrity over fluent hallucination", "Role-specific agents specialized in safety and planning"]
  },
  {
    id: "tang-2024-collaborators",
    title: "MEDAGENTS: Large Language Models as Collaborators for Zero-shot Medical Reasoning.",
    authors: ["Tang X", "Zou A", "Zhang Z", "Li Z", "Zhao Y", "Zhang X", "Cohan A", "Gerstein M"],
    year: 2024,
    journal: "Findings ACL",
    doi: "10.18653/v1/2024.findings-acl.33",
    abstract: "Five-step collaborative framework (專家 gather, Analysis, Report, Iterative Debate, Decision) for zero-shot clinical reasoning.",
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Excelled at mining internal expertise of base models", "Superior zero-shot performance on 9 datasets (MedQA, MMLU)", "Consensus-finding mechanism improves logical consistency"]
  },
  {
    id: "yang-2026-medaide",
    title: "MEDAIDE: Information fusion and anatomy of medical intents via LLM-based agent collaboration.",
    authors: ["Yang D", "Wei J", "Li M", "Liu J", "Liu L", "Hu M", "He J", "Ju Y", "Zhou W", "Liu Y", "Zhang L"],
    year: 2026,
    journal: "Information Fusion",
    doi: "10.1016/j.inffus.2025.103743",
    abstract: "Regularization-guided intent resolution system with rotation agent collaboration for information fusion in multi-round dialogues.",
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Outperforms base LLMs on 4 composite intent benchmarks", "Regularization module mitigates redundancy hallucinations", "Rotation mechanism ensures balanced peer review"]
  },
  {
    id: "liu-2026-magic",
    title: "Magic: AN LLM-based multi-agent activated graph-reasoning intelligent collaboration model for liver disease diagnosis.",
    authors: ["Liu B", "Nie Y", "Song H", "Lin Y", "Li J", "Weng X", "Su Z", "Suo Y", "Lv T", "Zhao X", "Yang J"],
    year: 2026,
    journal: "Information Fusion",
    doi: "10.1016/j.inffus.2025.103557",
    abstract: "Hybrid model adjusting relationship weights in knowledge graphs based on multi-agent debate results for liver diagnosis.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Specialized Diagnosis"],
    keyFindings: ["94.5% accuracy on Beijing Friendship Hospital dataset", "11.39% F1 improvement over SOTA baselines", "Verifies results with guidelines for clinical standard alignment"]
  },
  {
    id: "almeida-2025",
    title: "AI-Powered Automation in Healthcare: A Multi-agent Approach with LLM.",
    authors: ["Almeida M", "Machado J", "Sousa R", "Peixoto H"],
    year: 2025,
    journal: "CCIS",
    doi: "10.1007/978-3-032-05925-3_11",
    abstract: "Presets chatbot framework transforming natural language to FHIR/SQL queries to automate medical exam prescriptions.",
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Successfully streamlines repetitive clinician workflows", "Real-time records retrieval from patient databases", "Demonstrates operational efficiency gains"]
  },
  {
    id: "lu-2024-triage",
    title: "TRIAGEAGENT: Towards Better Multi-Agents Collaborations for Large Language Model-Based Clinical Triage.",
    authors: ["Lu M", "Ho B", "Ren D", "Wang X"],
    year: 2024,
    journal: "Findings EMNLP",
    doi: "10.18653/v1/2024.findings-emnlp.329",
    abstract: "Self-confidence and early-stopping mechanisms integrated into role-playing triage agents referencing the ESI handbook.",
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS for Healthcare Workflow", "LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["First public benchmark dataset for ESI-level triage", "Outperforms both coarse and fine-grained state-of-the-art baselines", "Transparent knowledge retrieval from ESI handbooks"]
  }
];
