import { Paper } from './types';

type PaperInit = Omit<Paper, 'reviewStatus'>;

export const PAPERS_PART2: PaperInit[] = [
  {
    id: "wang-2026-epidemic",
    title: "An LLM-Driven Multi-Agent Simulation Framework for Coupled Epidemic-Economic Dynamics.",
    authors: ["Wang S", "Liu H", "Zhang S", "Yang Q"],
    year: 2026,
    journal: "Information (Switzerland)",
    doi: "10.3390/info17030259",
    abstract: "Uses LLM agents with Perception-Deliberation-Action loops to autonomously balance health risks against economic necessity in crisis simulations.",
    tags: [],
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Generates adaptive human-like behaviors without scripting", "Bridged gap between micro-level cognition and macro societal outcomes", "Quantifies trade-offs between public health and stability"]
  },
  {
    id: "demaio-2025",
    title: "Privacy-Preserving Healthcare Data Interactions: A Multi-Agent Approach Using LLMs.",
    authors: ["De Maio C", "Fenza G", "Furno D", "Grauso T", "Loia V"],
    year: 2025,
    journal: "J Commun Softw Syst",
    doi: "10.24138/jcomss-2024-0119",
    abstract: "Dual-pathway design for secure interactions with EHRs, featuring a Data Update Agent (DUA) for real-time records auditing.",
    tags: [],
    themes: ["LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["Improved scalability and fault tolerance in clinical environments", "Privacy-compliant records update mechanism", "Robust handling of noisy inputs and complex queries"]
  },
  {
    id: "shang-2025",
    title: "Collaboration among Multiple Large Language Models for Medical Question Answering.",
    authors: ["Shang K", "Chang CH", "Yang CC"],
    year: 2025,
    journal: "IEEE ICHI",
    doi: "10.1109/ICHI64645.2025.00052",
    abstract: "Framework boosting reasoning and alleviating divergence among models of different expertise via collaborative confidence measurements.",
    tags: [],
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Boosts reasoning ability of all participating models", "Correlation found between LLM confidence and prediction accuracy", "Synergic effect observed from baseline diversity"]
  },
  {
    id: "althaf-2025",
    title: "Multi-Agent RAG Framework for Entity Resolution in Administrative Data.",
    authors: ["Althaf AM", "Mohammed MA", "Milanova M", "Talburt J", "Cakmak MC"],
    year: 2025,
    journal: "Computers",
    doi: "10.3390/computers14120525",
    abstract: "Decomposes household entity resolution into four agents (Matching, Linkage, Clustering, Movement Detection) using LangGraph.",
    tags: [],
    themes: ["LLM-based MAS for Healthcare Workflow"],
    keyFindings: ["61% reduction in API calls vs single-LLM baselines", "94.3% accuracy on name variation matching", "Traceable and interpretable decision processes"]
  },
  {
    id: "ogdu-2025",
    title: "An Adaptive Multi-Agent LLM-Based CDSS Integrating Biomedical RAG and Web Intelligence.",
    authors: ["Öğdü CU", "Arslanoğlu K", "Karaköse M"],
    year: 2025,
    journal: "IEEE Access",
    doi: "10.1109/ACCESS.2025.3613340",
    abstract: "Multi-layered adaptive system performing symptom analysis cross-validation with BioBERT-based RAG and real-time web intelligence.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["94% accuracy on MedQA", "Confidence calibration reduces hallucination", "Dynamic data fusion from multi-source up-to-date resources"]
  },
  {
    id: "fan-2025-hospital",
    title: "AI Hospital: Benchmarking Large Language Models in a Multi-agent Medical Interaction Simulator.",
    authors: ["Fan Z", "Wei L", "Tang J", "Chen W", "Wang S", "Wei Z", "Xie J", "Huang F", "Zhou J"],
    year: 2025,
    journal: "Proc COLING",
    doi: "N/A",
    abstract: "Simulator for dynamic medical interactions (Doctor player vs Patient/Examiner NPCs) to quantify symbol collection and diagnosis tasks.",
    tags: [],
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["Identified significant performance gaps in interactive scenarios", "Dispute resolution mechanism improves Reasoning", "MVME benchmark released for Chinese medical records"]
  },
  {
    id: "liang-2025-diet",
    title: "Exploring Multi-LLM Collaboration to Power Conversational Recommender System: Dietary Recommendation Case Study.",
    authors: ["Liang M", "Luo Y"],
    year: 2025,
    journal: "ACM CUI",
    doi: "10.1145/3719160.3737635",
    abstract: "Compares single vs multi-LLM phases for adaptation to user food preferences and nutrition requirements.",
    tags: [],
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Greater adaptability to conversational contexts", "Delivers more nutritionally balanced recommendations", "Improved user-centered experience"]
  },
  {
    id: "ozgun-2025",
    title: "Trustworthy AI Psychotherapy: Multi-Agent LLM Workflow for counseling and diagnosis.",
    authors: ["Ozgun MC", "Pei J", "Hindriks K", "Donatelli L", "Liu Q", "Wang J"],
    year: 2025,
    journal: "ACM CIKM",
    doi: "10.1145/3746252.3761164",
    abstract: "DSM5AgentFlow framework simulating therapist-client dialogues to generate DSM-5 Level-1 diagnostic questionnaires.",
    tags: [],
    themes: ["LLM-based MAS in Mental Health", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Autonomous generation of diagnostic questionnaires", "Explainable step-by-step disorder predictions", "Aligns outputs with expert psychiatric reasoning"]
  },
  {
    id: "han-2025-ed",
    title: "Multi-Agent CDSS for Korean Triage and Treatment Planning in Emergency Departments.",
    authors: ["Han S", "Choi W"],
    year: 2025,
    journal: "Adv AI ML",
    doi: "10.54364/AAIML.2025.51187",
    abstract: "Llama-3-70b based system with specialized agents (Nurse, Physician, Pharmacist, Coordinator) emulating key ED roles.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS for Healthcare Workflow", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Alleviates ED overcrowding via efficient triage", "Significantly higher accuracy than single-agent systems", "Robust findings in resource allocation tasks"]
  },
  {
    id: "xie-2024-kerap",
    title: "KERAP: A Knowledge-Enhanced Reasoning Approach for Accurate Zero-shot Diagnosis.",
    authors: ["Xie Y", "Cui H", "Zhang Z", "Lu J", "Shu K", "Nahab F", "Hu X", "Yang C"],
    year: 2024,
    journal: "AMIA Annu Symp Proc",
    doi: "N/A",
    abstract: "Three-agent architecture (Linkage, Retrieval, Prediction) refining zero-shot diagnosis via Knowledge Graph enhancement.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Scalable solution for zero-shot prediction", "Increases reliability without supervised training", "Attribute mapping agents reduce feature misalignment"]
  },
  {
    id: "lin-2026-atcmd",
    title: "ATCMD-Bench: Agentic Traditional Chinese Medicine diagnosis benchmark.",
    authors: ["Lin J", "Dai G", "Peng W", "Huang S", "Lao Y", "Zhang H", "Chen T"],
    year: 2026,
    journal: "Pattern Recognition",
    doi: "10.1016/j.patcog.2026.113679",
    abstract: "Unifies dynamic diagnostic environments and scorer metrics for TCM clinical diagnosis evaluation.",
    tags: [],
    themes: ["LLM-based MAS Surveys & Benchmarks", "LLM-based MAS in Specialized Diagnosis"],
    keyFindings: ["Simulates syndrome differentiation interactions in TCM", "Reveals limitations in current LLM syndrome reasoning", "Scoring metrics for reliable TCM clinical assessment"]
  },
  {
    id: "chen-2025-rare",
    title: "Enhancing diagnostic capability with multi-agents conversational large language models.",
    authors: ["Chen X", "Yi H", "You M", "Liu W", "Wang L", "Li H", "Zhang X", "Guo Y", "Fan L", "Chen G", "Lao Q", "Fu W", "Li K", "Li J"],
    year: 2025,
    journal: "npj Digit Med",
    doi: "10.1038/s41746-025-01550-0",
    abstract: "Multi-Agent Conversation (MAC) framework inspired by multidisciplinary teams for diagnosing rare diseases.",
    tags: [],
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Specialized Diagnosis", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Outperformed GPT-4 single-model consultations", "Optimal performance with 4 doctor agents and 1 supervisor", "80% top-1 diagnosis rate achieved in peer rounds"]
  },
  {
    id: "zuo-2025-kg4diagnosis",
    title: "KG4Diagnosis: A Hierarchical Multi-Agent LLM Framework with Knowledge Graph Enhancement.",
    authors: ["Zuo K", "Jiang Y", "Mo F", "Liò P"],
    year: 2025,
    journal: "PMLR",
    doi: "N/A",
    abstract: "Two-tier architecture (GP agent + Specialized agents) combining LLMs with automated KG construction across 362 diseases.",
    tags: [],
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Semantic-driven relationship reconstruction", "Human-guided reasoning expansion", "Extensible foundations for medical domain specific agents"]
  },
  {
    id: "bu-2026-biomedagent",
    title: "Empowering AI data scientists using BioMedAgent: A self-evolving multi-agent framework.",
    authors: ["Bu D", "Sun J", "Li K", "He Z", "Huang W", "Hu J", "Zhang S", "Lei S", "Huo P", "Wang Z", "Wang S", "Wang T", "Gao K", "Wu Y", "Zhao L", "Wang K", "Li G", "Song H", "Jin Y", "Zhang K", "Chen R", "Zhao Y"],
    year: 2026,
    journal: "Nat Biomed Eng",
    doi: "10.1038/s41551-026-01634-6",
    abstract: "BioMedAgent chains bioinformatics tools into workflows for autonomous cross-omics analysis and image segmentation.",
    tags: [],
    themes: ["LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["77% success rate on BioMed-AQA tasks", "Self-evolving memory retrieval for tool use", "Generalized robustly to BixBench dataset"]
  },
  {
    id: "han-2025-dialogue",
    title: "Research and implementation of medical dialogue mechanism based on LLM and multi-agent collaboration.",
    authors: ["Han T", "Li X", "Li A", "Zhou X", "Yang Z"],
    year: 2025,
    journal: "Proc SPIE",
    doi: "10.1117/12.3088636",
    abstract: "Three-layer dynamic framework (Independent, Interaction, Collaboration) resolving conflicts via knowledge-graph integration.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Significant improvement over single-model diagnostics", "Emphasis on traceable reasoning paths", "Visualized decision processes addressing AI black-box"]
  },
  {
    id: "yue-2024-clinicalagent",
    title: "ClinicalAgent: Clinical Trial Multi-Agent System with Large Language Model-based Reasoning.",
    authors: ["Yue L", "Xing S", "Chen J", "Fu T"],
    year: 2024,
    journal: "ACM BCB",
    doi: "10.1145/3698587.3701359",
    abstract: "LEAST-TO-MOST and ReAct reasoning integrated into a multi-agent system for predicting trial outcomes.",
    tags: [],
    themes: ["LLM-based MAS in Oncology", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["0.7908 PR-AUC in outcome prediction", "33% gain over standard prompting", "Enables aggregation of latest external medical trial evidence"]
  },
  {
    id: "blitti-2026",
    title: "LieToMe: A Multi-Agent System for Detecting Hallucinations in Large Language Models.",
    authors: ["Blitti KEK", "Tola FG", "Shukla M", "Ladva V", "Dholakia N"],
    year: 2026,
    journal: "CCIS",
    doi: "10.1007/978-3-032-17834-3_29",
    abstract: "Worker agents (RAG, Web, Domain-based) compute a Composite Hallucination Score (CHS) to verify critical healthcare responses.",
    tags: [],
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Highly modular system for critical domains", "Detected errors accurately where single models failed", "Composite scoring Weights adaptable per domain"]
  },
  {
    id: "ma-2026-medla",
    title: "MedLA: A Logic-Driven Multi-Agent Framework for Complex Medical Reasoning.",
    authors: ["Ma S", "Huang J", "Zhang F", "Shen Y", "Wu J", "Fan G", "Zhang Z", "Zang Z"],
    year: 2026,
    journal: "Proc AAAI",
    doi: "10.1609/aaai.v40i2.37052",
    abstract: "Logic-driven graphs and syllogistic triads enabling premise-level alignment and contradiction resolution.",
    tags: [],
    themes: ["LLM-based MAS versus Single LLM in Healthcare", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["SOTA performance on MedDDx", "Transparency via explicit logical trees", "Scales effectively across diverse model backbones"]
  },
  {
    id: "gu-2024-mentaler",
    title: "MENTALER: Toward Professional Mental Health Support with LLMs via Multi-Role Collaboration.",
    authors: ["Gu Z", "Zhu Q"],
    year: 2024,
    journal: "IEEE BIBM",
    doi: "10.1109/BIBM62325.2024.10822643",
    abstract: "Multi-role architecture (Analyzer, Knowledge-Collector, Strategy-Planner) for diagnostic and therapeutic support.",
    tags: [],
    themes: ["LLM-based MAS in Mental Health", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Highly fluent and professional support strategies", "Exemplar retrieval reduces generic advice", "Clinically aligned diagnostic summaries"]
  },
  {
    id: "zhong-2025-sequencing",
    title: "Multi-Agent LLM Reasoning for Clinical Procedure Sequencing from High-Granularity EHR Data.",
    authors: ["Zhong Y", "Shi W", "Tamo JB", "Nnamdi MC", "Yuan Y", "Wang MD"],
    year: 2025,
    journal: "ACM BCB",
    doi: "10.1145/3765612.3767238",
    abstract: "Simulates Consensus vs Leader-based organizational models for specialty-specific procedure recommendations.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS with Role-playing Agents in Healthcare"],
    keyFindings: ["Leader-based model outperforms consensus", "Higher accuracy in procedural sequencing MRR", "Reasoning grounded in specialty-specific PubMed domains"]
  },
  {
    id: "lee-2025-soap",
    title: "Automated Clinical Problem Detection from SOAP Notes using a Collaborative Multi-Agent LLM Architecture.",
    authors: ["Lee Y", "Wang X", "Yang C"],
    year: 2025,
    journal: "ACM BCB",
    doi: "10.1145/3765612.3767792",
    abstract: "Enforces inference from subjective/objective notes to detect problems rather than simple keyword lookup.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Fragility of single-agent models noted", "Captures clinical team dynamics for problem list matching", "Reduced false positives in clinical problem identification"]
  },
  {
    id: "kim-2025-cancer",
    title: "Evaluation of Multi-Agent LLMs in Multidisciplinary Team Decision-Making for Challenging Cancer Cases.",
    authors: ["Kim J", "Lee B", "Sohn KA", "Kim D", "Chan Lee Y"],
    year: 2025,
    journal: "PMLR",
    doi: "N/A",
    abstract: "Assesses alignment with human experts in cancer MDT meetings for consensus-based oncology decisions.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS in Oncology"],
    keyFindings: ["Multi-agent systems aligned better with experts than single LLMs", "Balances diverse valid treatment options effectively", "Lays groundwork for decision support integration in MDTs"]
  },
  {
    id: "patel-2025-mistral",
    title: "Fine-Tuned Mistral Model for Multi-Agent Mental Health Counseling System.",
    authors: ["Patel A", "Lohumi P", "Shah V", "Dash M", "Arya MS"],
    year: 2025,
    journal: "ICCAI",
    doi: "10.1109/ICCAI66501.2025.00056",
    abstract: "Diagnostic and counseling agent personas fine-tuned on mental health social media expression datasets.",
    tags: [],
    themes: ["LLM-based MAS in Mental Health"],
    keyFindings: ["Improved scalability of counseling services", "Personalized support for varied psychiatric concerns", "Effective detection of stress/depression intents"]
  },
  {
    id: "aghaee-2026-simulation",
    title: "SynthAgent: A Multi-Agent LLM Framework for Realistic Patient Simulation.",
    authors: ["Aghaee A", "Asgarian S", "Jeon J"],
    year: 2026,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Simulates realistic patient journeys for obesity with comorbidities to train clinical staff and test intervention systems.",
    tags: [],
    themes: ["LLM-based MAS with Role-playing Agents in Healthcare", "LLM-based MAS in Mental Health"],
    keyFindings: ["Emulates comorbidity histories from medical claims", "Highly realistic simulated case transitions", "Valuable tool for behavioral intervention training"]
  },
  {
    id: "leite-2026-sickle",
    title: "LLM-Based Multi-Agent System with RAG for Medical Care Planning in Sickle Cell Disease.",
    authors: ["Leite LB", "Pereira DE"],
    year: 2026,
    journal: "ACM Proc",
    doi: "N/A",
    abstract: "Generates personalized medical care plans for SCD patients by grounding collaborative reasoning in hematology RAG.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Increases care plan specificity", "Accurate adherence to rare disease guidelines", "Reduces variations in clinical planning"]
  },
  {
    id: "almasoud-2026-rare",
    title: "Evaluating Multi-Agent LLM Architectures for Rare Disease Diagnosis.",
    authors: ["Almasoud A"],
    year: 2026,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Compares various multi-agent patterns (Chain, Parallel, Graph) for robustness in low-prevalence disease diagnostics.",
    tags: [],
    themes: ["LLM-based MAS in Specialized Diagnosis"],
    keyFindings: ["Graph-based architectures excel in complex cases", "Theoretical multi-agent advancements successfully applied to rare scenarios", "Improved confidence calibration over flat agents"]
  },
  {
    id: "giuffre-2026-tumor",
    title: "A Multi-Agent Large Language Model Framework that Simulates a Multidisciplinary Tumor Board.",
    authors: ["Giuffrè M", "Ma F", "Visintin A", "Fusaro L", "Gulotta M"],
    year: 2026,
    journal: "Dig Liver Dis",
    doi: "N/A",
    abstract: "Specifically tailored for hepatocellular carcinoma management simulating clinical consensus boards.",
    tags: [],
    themes: ["LLM-based MAS in Oncology", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Guidelines-grounded multi-agent system performed best", "Reduction in management disagreement", "Better emulation of human tumor board reasoning"]
  },
  {
    id: "chen-2025-medsentry",
    title: "Medsentry: Understanding and mitigating safety risks in medical llm multi-agent systems.",
    authors: ["Chen K", "Zhen T", "Wang H", "Liu K", "Li X", "Huo J"],
    year: 2025,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Analyzes systemic risks when role-specific experts interact, proposing safety filter agents to mitigate escalation.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Identification of interaction-specific safety risks", "Safety filter agent effectively blocks inaccurate escalations", "Proposed protocol for risk-aware clinical agent design"]
  },
  {
    id: "xu-2025-emotional",
    title: "Multiagentesc: A llm-based multi-agent collaboration framework for emotional support conversation.",
    authors: ["Xu Y", "Hu J", "Zhao Z", "Duan Z", "Sun X"],
    year: 2025,
    journal: "ACM Proc",
    doi: "N/A",
    abstract: "Multi-agent debate and cooperation strategies for empathetic response generation in mental health support.",
    tags: [],
    themes: ["LLM-based MAS in Mental Health"],
    keyFindings: ["System chosen via multi-agent debate achieved higher empathy", "Significant improvement in conversation coherence", "Empathy-specific personas outperform flat models"]
  },
  {
    id: "greene-2025-psychiatrist",
    title: "AI psychiatrist assistant: an LLM-based multi-agent system for depression assessment.",
    authors: ["Greene A", "Blair N", "Aghabagher SM"],
    year: 2025,
    journal: "Learning for Health",
    doi: "N/A",
    abstract: "Automates depression screening from clinical interviews using collaborative specialists.",
    tags: [],
    themes: ["LLM-based MAS in Mental Health"],
    keyFindings: ["High semantic depth in medical text capture", "Accurate PHQ-9 alignment from open-ended text", "Collaborative agents improve diagnostic sensitivity"]
  },
  {
    id: "chen-2025-mdteamgpt",
    title: "Mdteamgpt: A self-evolving llm-based multi-agent framework for multi-disciplinary team consultation.",
    authors: ["Chen K", "Li X", "Yang T", "Wang H", "Dong W"],
    year: 2025,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Residual discussion structures allowing consultation records to evolve and correct reasoning in future cases.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Self-evolving capabilities lead to better longitudinal consistency", "Residual structures prevent information loss in deep rounds", "High expert alignment in MDT simulations"]
  },
  {
    id: "lin-2025-survey",
    title: "A Survey of LLM-based Multi-agent Systems in Medicine.",
    authors: ["Lin Y", "Xu S", "Zhang W", "Sun Y", "Chen Z", "Zhang Y"],
    year: 2025,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Comprehensive taxonomy of coordination mechanisms, reasoning patterns, and clinical domains in medical MAS.",
    tags: [],
    themes: ["LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["Identified reasoning joint-optimization as key trend", "Taxonomy of medical specialty-agent alignments", "Highlighted safety as primary deployment barrier"]
  },
  {
    id: "yao-2025-hospital-survey",
    title: "A survey on llm-based multi-agent ai hospital.",
    authors: ["Yao Z", "Yu H"],
    year: 2025,
    journal: "OSF",
    doi: "N/A",
    abstract: "Examines the shift toward full-workflow automation in simulated 'AI Hospitals' using multi-specialty agent swarms.",
    tags: [],
    themes: ["LLM-based MAS Surveys & Benchmarks"],
    keyFindings: ["Taxonomy of orchestration strategies (Hierarchical vs Flat)", "Focus on end-to-end automation in high-throughput environments", "Highlight gaps in prospective clinical trial evaluations"]
  },
  {
    id: "jia-2025-ddo",
    title: "DDO: Dual-decision optimization for LLM-based medical consultation via multi-agent collaboration.",
    authors: ["Jia Z", "Jia M", "Duan J", "Wang J"],
    year: 2025,
    journal: "ACM Proc",
    doi: "N/A",
    abstract: "Optimizes dual-decision nature of medical consultation (Diagnosis + Treatment) through specialized collaborative loops.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Significant reduction in treatment inconsistencies", "Balanced focus between diagnostic depth and planning feasibility", "Collaborative loops reduce cross-module errors"]
  },
  {
    id: "lee-2025-reliable",
    title: "Reliable decision-making for multi-agent llm systems.",
    authors: ["Lee XY", "Akatsuka S", "Vidyaratne L", "Kumar A"],
    year: 2025,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Explores Majority Voting and Decentralized architectures for improving the reliability of autonomous healthcare agents.",
    tags: [],
    themes: ["LLM-based MAS in Clinical Decision-making", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Majority voting found to be most robust architecture", "Decentralized models reduce single-point model failures", "Significant reliability gain at scale"]
  },
  {
    id: "luo-2025-psychosocial",
    title: "DialogGuard: Multi-Agent Psychosocial Safety Evaluation of Sensitive LLM Responses.",
    authors: ["Luo H", "Laban G"],
    year: 2025,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Evaluates sensitive healthcare responses using PKU-SafeRLHF and multi-agent judging protocols.",
    tags: [],
    themes: ["LLM-based MAS in Mental Health", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Detected psychosocial risks with higher accuracy than single-agent models", "Crucial for therapeutic LLM deployments", "Proposed safety judging protocols for psychiatric AI"]
  },
  {
    id: "ma-2024-ehrflow",
    title: "Ehrflow: A large language model-driven iterative multi-agent EHR data analysis workflow.",
    authors: ["Ma L", "Wang Y", "Pan C", "Harrison EM", "Gao J"],
    year: 2024,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Iterative workflow manager chaining agents for data cleaning, transformation, and clinical hypothesis testing.",
    tags: [],
    themes: ["LLM-based MAS for Healthcare Workflow", "LLM-based MAS versus Single LLM in Healthcare"],
    keyFindings: ["Automates complex EHR data science tasks", "Reduced manual coding time for physicians", "Transparent iteration logs for verification"]
  },
  {
    id: "liu-2024-drug-prog",
    title: "Drugagent: Automating ai-aided drug discovery programming through llm multi-agent collaboration.",
    authors: ["Liu S", "Lu Y", "Chen S", "Hu X", "Zhao J"],
    year: 2024,
    journal: "arXiv",
    doi: "N/A",
    abstract: "Unifies machine learning programming with deep biomedical domain expertise for automated discovery pipelines.",
    tags: [],
    themes: ["LLM-based MAS for Pharmacology", "LLM-based MAS in Clinical Decision-making"],
    keyFindings: ["Autonomous generation of discovery workflows", "Reduces skill barrier for computational drug design", "Superiority in handling multi-tool integration"]
  }
];
